# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt-get install python3-venv
    python3 -m venv venv
    source ./venv/bin/activate
    python -m pip install --upgrade pip
    python -m pip install -r requirements.txt
    python -m pip install twine
    python setup.py sdist bdist_wheel
  displayName: 'Set up the env'

- script: |
    ./edb2cve.py _workdir/exploitdb
  displayName: 'Build the mappings'